### ISSUE TITLE
Autofeaturing seems to not account for newer versions with broader support ranges entirely overlapping older versions

### ISSUE THREAD

**Issue by Ampflower** [modrinth/knossos#1512] opened 2024-01-07 03:19 UTC
### Describe the bug

Every version of a given mod is featured regardless of whether a newer version satisfies the same loader + game version

### Steps to reproduce

1. Navigate to ~~https://modrinth.com/mod/fabric-api~~ or any other mod with multiple versions for the same game version and loader
   Fabric API's page was since fixed; current samples are: 
   - https://modrinth.com/mod/quickbench
   - https://modrinth.com/mod/polysit
   Both of which notably have version ranges that don't 1:1 overlap, but rather relied on the newer supporting version having a broader range to be an update, and thus hide older versions.
2. Wait for it to load
3. Observe the featured list and the accompanying scrollbar

### Expected behavior

For the latest version of each mod for a given loader and game version, without any prior versions being entirely overlapped by a newer version.

### Additional context

This appears like a Knossos bug as far as I can tell as the API doesn't seem to have featured versions as a field?
Tho I could be wrong.

**Comment by Ampflower** [comment] 2024-01-07 08:10
Seems that Fabric API's page was fixed but not for https://modrinth.com/mod/quickbench

**Comment by Prospector** [comment] 2024-01-07 08:25
That's working as intended, it's promoting all the versions it needs to in order to feature all versions we consider "major"

**Comment by Ampflower** [comment] 2024-01-07 08:26
Erm.. it's not doing so as I expected it would from before:
![image](https://github.com/modrinth/knossos/assets/8528256/43aa60c6-5ae8-404e-9f46-21deaa59b18c)

It shouldn't be promoting a stale beta or an older version (the bottom-most two)

**Comment by Prospector** [comment] 2024-01-07 08:45
ah, yeah I misread the ranges

**Comment by Estecka** [comment] 2024-01-07 14:47
In some cases it doesn't even promote newer versions. For these two, the newer v1.1 are completely ignored, only v1.0 are  featured :
https://modrinth.com/mod/packrule-menus/versions
https://modrinth.com/mod/shifting-wares/versions

Overall, across all my mods, a newer mod-versions is only featured if it covers a minecraft-version that wasn't already covered by an older mod-version.

In short, it looks to me like, auto-feature simply has the concept of "older" and "newer" versions mixed up.

**Comment by triphora** [comment] 2024-01-07 21:22
Fixed in modrinth/labrinth#836

**Closed by triphora** 2024-01-07 21:22 UTC
Labels: bug
