### ISSUE TITLE
Filtering loaders and game versions together does not specifically look for them on the same version

### ISSUE THREAD

**Issue by mist475** [modrinth/knossos#447] opened 2022-04-04 09:21 UTC
### Environment

Website

### Describe the bug

If you select a specific mod loader and version (for example "forge" & "1.7.10") you get all mods that have a forge version and a 1.7.10 version. This includes mods whose 1.7.10 version isn't on forge.

For Example:
![image](https://user-images.githubusercontent.com/70655895/161511937-e5cfc427-85b4-4025-b7fa-59705940a56a.png)

Of the mods listed here the odd one out is Alternate Current, which has a 1.7.10 Legacy Fabric version but not a forge version (the only forge version of the mod listed is for 1.18)

### Steps To Reproduce

1 Go to https://modrinth.com/mods
2 Select "Forge" in Loaders
3 Select "1.7.10" in versions
4 Click on "Alternate Current"
5 Click on "Versions"
6 Select "Forge" as Loader
7 Only 1.18 is shown

### Expected behavior

Only mods whose 1.7.10 version uses Forge should show up

**Comment by MagnusHJensen** [comment] 2023-02-17 21:51
I can't reproduce this error.
Seems to sort fine now.

**Comment by Prospector** [comment] 2023-02-17 21:54
It's still a problem, but it's a labrinth problem, not a knossos problem.

See: https://modrinth.com/mods?q=not%20enough%20wands&g=categories%3A%27fabric%27&v=1.19.3

Not Enough Wands has a fabric version and a 1.19.3 version, but not a fabric and 1.19.3 version, which is what the user is trying to look for.

**Comment by Andre601** [comment] 2023-02-17 21:59
> Not Enough Wands has a fabric version and a 1.19.3 version, but not a fabric and 1.19.3 version, which is what the user is trying to look for.

I think you made a typo here?

**Comment by MagnusHJensen** [comment] 2023-02-17 22:01
Odd.
The example mentioned by OP is not a problem anymore.

**Comment by Prospector** [comment] 2023-02-17 22:03
> The example mentioned by OP is not a problem anymore.

well it seems the mod doesn't exist anymore so that would be why

**Comment by MagnusHJensen** [comment] 2023-02-17 22:07
Right here: https://modrinth.com/mod/alternate-current

**Comment by Prospector** [comment] 2023-02-17 22:18
ah, I see the 1.7.10 version just doesn't exist anymore.

**Comment by triphora** [comment] 2024-01-28 21:23
Fixed as of modrinth/labrinth#731

**Closed by triphora** 2024-01-28 21:23 UTC
Labels: bug
