### ISSUE TITLE
Mark a mod/modpack version as yanked

### ISSUE THREAD

**Issue by OriginCode** [modrinth/knossos#577] opened 2022-07-23 09:43 UTC
### Is your feature request related to a problem? Please describe.

A problematic version can sometimes be released. The author can yank a version so the players can get warned.

### Describe the solution you'd like

Add a button to yank a version on the version editing page. Display the yank status along with the version.

When clicking the download button, warn the user that the version is yanked.

### Describe alternatives you've considered

Hide the yanked versions and list them in another tab.

### Additional context

N/A

**Comment by wafflecoffee** [comment] 2022-07-23 13:34
I feel like this was just an excuse for you to say "yank" multiple times in rapid succession. The correct term, however, is "to yeet".

Duplicate of modrinth/labrinth#318

**Closed by wafflecoffee** 2022-07-23 13:34 UTC
Labels: feature request
