### ISSUE TITLE
steam deck resolution/aspect ratio issue

### ISSUE THREAD

**Issue by OrdinaryCloverOC** [modrinth/knossos#1007] opened 2023-02-20 19:12 UTC
### Describe the bug

steam deck is 16:10 (10:16 on it's side) it is cut off slightly on the right side. default resolution too.

### Steps to reproduce

go to modrinth on firefox steam deck.

### Expected behavior

not being cut off

### Additional context

screenshot in discord support, it doesn't let me upload images on my browser. probably a setting i need to change.

**Comment by MMK21Hub** [comment] 2023-02-26 14:24
Just to clarify, this issue can be reproduced on any device by resizing your viewport width to 1280px.

Here's a screenshot of [the Mods search page](https://modrinth.com/mods) that demonstrates the issue. As you can see, the project cards and search controls overflow on the right edge.
![](https://user-images.githubusercontent.com/50421330/221413119-fffe97ce-7da1-401b-9e3f-a02449fb9f4c.png)

Here's a list of all the pages that are affected by this bug, based on [a GitHub search query](https://github.com/search?q=repo%3Amodrinth%2Fknossos+%5C%22normal-page__content%22&type=code):
- [**Legal**](https://modrinth.com/legal)
- [**Moderation**](https://modrinth.com/moderation) (Not tested)
- Project pages
- **[Dashboard](https://modrinth.com/dashboard)**
- Search pages
- **[Settings](https://modrinth.com/settings)**
- **[Notifications](https://modrinth.com/notifications)**
- User pages

### Code analysis

This issue appears to be caused by [a single CSS rule in `layout.scss`](https://github.com/modrinth/knossos/blob/6c3b87c9b9098b30d12cee4af2f5fc5f9f25e6a6/assets/styles/layout.scss#L100).
```scss
@media (min-width: 80rem) {
  .normal-page__content {
    width: calc(60rem - .75rem);
  }
}
```
This forces the page content (i.e. everything to the right of the sidebar) to be `59.25rem` wide, preventing it from narrowing to fit within the viewport when the viewport becomes narrow.

The media query `min-width: 80rem` prevents this issue from occurring at viewport widths below 80rem (1280px).

As far as I can tell, this CSS rule is redundant and can be removed without any side effects. This is because [`layout.scss` also sets a `max-width` for the `.normal-page__content` element](https://github.com/modrinth/knossos/blob/6c3b87c9b9098b30d12cee4af2f5fc5f9f25e6a6/assets/styles/layout.scss#L94), preventing the content from getting too big on wider viewports. I have tested this using DevTools, confirming my idea.

I believe that the erroneous rule is a leftover from the flexbox layout that was replaced in #777.

**Comment by triphora** [comment] 2023-03-09 22:01
Duplicate of #822

**Closed by triphora** 2023-03-09 22:01 UTC
