### ISSUE TITLE
User profiles don't work when GitHub is blocked

### ISSUE THREAD

**Issue by ShockedCoder** [modrinth/knossos#588] opened 2022-08-01 20:31 UTC
### Environment

Website

### Describe the bug

When clicking on usernames it takes you to a page where it says that the user doesn't exist. This happened for every user I tried.

### Steps To Reproduce

1. Go to any mod or search for anything
2. Click on anyone's username
3. profit

### Expected behavior

Shows the user profile and all of their mods and modpacks

**Comment by wafflecoffee** [comment] 2022-08-01 20:34
https://user-images.githubusercontent.com/60205699/182242095-1a8eff20-1dff-4a37-a5b1-9e663a08df1c.mp4
Unable to reproduce

**Comment by FavoritoHJS** [comment] 2022-10-02 16:43
Bump, can reproduce... if github is blocked. I suspect @ShockedCoder was running agressive NoScript settings or something similar

Interestingly, even in that case you _can_ get the user to show up by reloading the page...

**Comment by ShockedCoder** [comment] 2022-10-02 21:53
I have uMatrix and I didn't think it'd be necessary to enable Github when going to people's Modrinth profiles.

I haven't checked if enabling it would work, I'll check in the morning.

**Comment by FavoritoHJS** [comment] 2022-10-03 02:03
I suspect the github account integration means that whatever gets the user also phones to github, and if that call falls, it explodes.

Now as for why reloading fixes it... please let it be a real issue and not NoScript letting things through

**Comment by ShockedCoder** [comment] 2022-10-03 13:20
> Now as for why reloading fixes it... please let it be a real issue and not NoScript letting things through
# SKIBIDI
https://user-images.githubusercontent.com/40272709/193587193-a49f961e-f33c-4223-aa93-bb65550d3c7a.mp4

It literally breaks just from not being able to send and receive **one** XHR request

**Comment by triphora** [comment] 2022-11-21 03:01
Fixed in #758

**Closed by triphora** 2022-11-21 03:01 UTC
Labels: bug

**Comment by FavoritoHJS** [comment] 2022-11-21 03:35
Checked, it works.
