### ISSUE TITLE
Page for listing formatting options

### ISSUE THREAD

**Issue by Andre601** [modrinth/knossos#615] opened 2022-08-18 19:05 UTC
### Is your feature request related to a problem? Please describe.

There is currently no location to obtain knowledge about all supported markdown and HTML formatting options available in Modrinth.

### Describe the solution you'd like

A page should be added that lists all available formatting options for Markdown and HTML (Where no Markdown equivalent is present), so that people know what they can put into their project pages.

If you feel really fancy could perhaps also the text boxes receive an update, to have a sort of editor being used (Similar to how GitHub has one) to more easily insert features like the `<kbd>` tag.

### Describe alternatives you've considered

Just trial and error...

**Comment by jadelily18** [comment] 2022-08-19 01:55
okay so there's a few ways to do this, but I'm not sure which one most people would like better. 

1. creating another page on the regular frontend site and just linking to it from the text editor
2. creating another page on the docs site and linking to it 
3. using a modal

i *kinda* lean towards the modal one because it can just be a single component and not its own page

**Comment by Andre601** [comment] 2022-09-04 12:35
There's now a PR on the docs repo, so perhaps this issue should be transferred to it...

**Comment by triphora** [comment] 2022-11-17 21:50
Fixed by modrinth/docs#64

**Comment by Minenash** [comment] 2022-11-18 07:53
I don't agree that [docs#64](https://github.com/modrinth/docs/pull/64) actually solves this issue at all.

That doc page includes some common markdown (and one html) formats (bold, italic, strikethrough, code, quotes, normal links, headings, lists, tables, and details), which is nice, but fails to tell the user what can and cannot be used in the description.

Everything but details is common gh-flavored markdown, and even details is a part of modrinth allowing most html tags. Nothing shows stuff that modrinth has that normal markdown/html doesn't or vice versa.

For example:
- It doesn't mention that HTML tags can be used
- that iframes, script, etc are blocked or are not supported
- that on modrinth links to youtube are displayed as embeds, and youtube iframes are an exception to the above
- that a lot of attributes (mainly the style one) can't be used

**Comment by Andre601** [comment] 2022-11-18 23:51
Feel free to open a new issue or (even better) make a PR to address those things.

I myself consider the basics covered. At most could YT videos be mentioned too, but that's about it I would say because:

- Why mention HTML? Markdown is specifically there as a user-friendlier replacement for HTML.  
  Also, Modrinth does link to GFM in the Markdown docs themself, so people probably can figure out themself that HTML is also working.
- I have doubts anyone really wants to try HTML-exclusive options like styling or similar. Especially when it's not mentioned that HTML works too.

I also see it like this: People that publish their stuff on Modrinth usually have had their encounters with Markdown somewhere, be it on GitHub, CurseForge, or some forum. And even if not is it not that difficult to find out how Markdown works in the end (At least the basic ones).

**Comment by Minenash** [comment] 2022-11-19 01:15
> Why mention HTML? Markdown is specifically there as a user-friendlier replacement for HTML.
Because markdown is limited (by design), and people may want to do more advance stuff. a ***lot*** of projects use html in their descriptions

> Also, Modrinth does link to GFM in the Markdown docs themself, so people probably can figure out themself that HTML is also working.
The best version of this page shouldn't rely on GFM. It includes a bunch of features not available to modrinth authors

> I have doubts anyone really wants to try HTML-exclusive options like styling or similar
The two most common use cases for styling is colors and text-alignment, and for authors coming from CF, the stripping of attributes, like style, has been brought up a lot through out the years.

> People that publish their stuff on Modrinth usually have had their encounters with Markdown somewhere, be it on GitHub, **CurseForge,** or some forum.
I don't know the percentages, but I believe CF's WYSIWYG is way more often used than markdown

> And even if not is it not that difficult to find out how Markdown works in the end (At least the basic ones).
I 100% agree, that's why I think this page should primary focus on the differences between modrinth's parser and plain markdown. Idrc if markdown basics are only linked to (though probably better that it's all one page)

**Comment by Prospector** [comment] 2024-01-30 03:34
I feel like this is effectively solved given the new editor has buttons for formatting and links to our resource on our support site.

**Closed by Prospector** 2024-01-30 03:34 UTC
Labels: enhancement

**Comment by Minenash** [comment] 2024-01-30 03:44
It's mostly solved, but I don't like how the page only includes stuff not in the editor. Not everyone writing stuff like change-logs are using the editor (for example, if you're using a tool that publishes to multiple places, or something that keep modrinth and github readme in sync). Especially the youtube one, as that's not standard markdown. It also makes it so the page doesn't fully answer it's own question

It would be nice to have a second page (or collapsed section) that does include stuff in the editor
