### ISSUE TITLE
Suggestion: Client/Server Categories

### ISSUE THREAD

**Issue by itsVyasi** [modrinth/knossos#107] opened 2021-02-22 06:19 UTC
I'm suggesting new categories for mods intended for only client usage or only server usage, and maybe unmarked mods show  with either to help visibility, but are sorted last.

**Comment by Sollace** [comment] 2021-03-07 23:02
+1

I'd like the same thing, though my thought was instead of categories make it a dropdown like what we already have for the MC version. Let it be a selection between Client/Server/Both

**Comment by Geometrically** [comment] 2021-03-27 03:59
Duplicate of #100

**Closed by Geometrically** 2021-03-27 03:59 UTC

**Comment by itsVyasi** [comment] 2021-03-27 04:44
Oops, somehow missed the other one, my bad.
